#!/usr/bin/env sh
#
# bspwm hotkeys
#

#
# wm independent hotkeys
#

control + super + s
    ~/.bw-scripts/slab.sh

control + super + 2
    ~/.bw-scripts/2fa.sh

control + super + u
    ~/.bw-scripts/unlock.sh
