#!/usr/bin/env sh
#
# bspwm hotkeys
#

#
# wm independent hotkeys
#

control + super + s
    /home/heywoodlh/.bw-scripts/slab.sh

control + super + 2
    /home/heywoodlh/.bw-scripts/2fa.sh

control + super + u
    /home/heywoodlh/.bw-scripts/unlock.sh
